micronaut:
  application:
    name: pixManagerRest


grpc:
  client:
    plaintext: true
    max-retry-attempts: 10

  channels:
    pix-manager:
      address: ${PIX_MANAGER_ADDRESS:`localhost:50051`}
      plaintext: true
      max-retry-attempts: 10

